spring:
  profiles:
    active: dev

  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3 #Minimo de Conexões
      idle-timeout: 10000 #Tempo Máximo de ociosidade

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
    serialization:
      fail-on-empty-beans: false

  #Assim habilita funcionalidades que não sobem no debug
  # exemplo NoHandlerFoundException
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  #Configuração para Envio de Email
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    #password:

  #Configuração de Locale Que vai substituir . por /
  freemarker:
    settings:
      locale: pt_BR


  #Confinguração de Tamanho de envio de envio de arquivo
  # e tamanho máximo para a requisição
  #servlet:
  #  multipart:
  #    max-file-size: 20KB
  #    max-request-size: 20MB

  #Implementando o resource server obrigatorio informar os dados
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://auth.algafood.local:8081/oauth/check_token
          client-id: checktoken
          client-secret: check123


  #Local de Armazenamento de Fotos local
algafood:
  storage:
    tipo: local
    local:
      diretorio-fotos: /home/roberto/Área de Trabalho/catalogo

    #Configurações da Amazon Cloud S3
    s3:
      id-chave-acesso: #id-chave-acesso
      chave-acesso-secreta: #chave-acesso-secreta
      bucket: algafood.roberto.aws.s3
      regiao: us-east-1
      diretorio-fotos: catalogo

  email:
    remetente: AlgaFood <carlosmedeiroslima1981@gmail.com>
    impl: fake
    sandbox:
      destinatario: teste@algafood.com.br

#Compressão com Gzip
server:
  compression:
    enabled: true
    mime-types: application/json

logging:
  loggly:
    token: #seu_customer_Token_aqui

