spring:
  profiles:
    active: dev

  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3 #Minimo de Conexões
      idle-timeout: 10000 #Tempo Máximo de ociosidade

  jackson:
    deserialization:
      fail-on-unknown-properties: true
      fail-on-ignored-properties: true
    serialization:
      fail-on-empty-beans: false

  #Assim habilita funcionalidades que não sobem no debug
  # exemplo NoHandlerFoundException
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  #Confinguração de Tamanho de envio de envio de arquivo
  # e tamanho máximo para a requisição
  #servlet:
  #  multipart:
  #    max-file-size: 20KB
  #    max-request-size: 20MB

  #Local de Armazenamento de Fotos local
algafood:
  storage:
    local:
      diretorio-fotos: /home/roberto/Área de Trabalho/catalogo






