#Configurações do Banco de Dados
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/app?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password: root

#Criação automática das tabelas
  jpa:
    #generate-ddl: true
    hibernate:
      #ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect